#!/bin/bash
# Linux/POSIX only, set up 2 build folders (debug & release) with cmake
# Optionally pass -b to also build both targets

BUILD=false
CORES=4
PROJECT_DIR=$PWD

# Read args
while getopts "bc:" opt; do
    case $opt in
        b)
            BUILD=true
            ;;
        c)
            CORES=$OPTARG
            echo "Building on "$CORES" cores"
            ;;

    esac
done

mkdir -p $PROJECT_DIR/build
mkdir -p $PROJECT_DIR/build/release
mkdir -p $PROJECT_DIR/build/debug

# Generate Debug build
cd $PROJECT_DIR/build/debug
cmake -DCMAKE_BUILD_TYPE=Debug $PROJECT_DIR

# Generate Release build
cd $PROJECT_DIR/build/release
cmake -DCMAKE_BUILD_TYPE=Release $PROJECT_DIR

if $BUILD; then
    cd $PROJECT_DIR/build/debug
    make -j$CORES
    cd $PROJECT_DIR/build/release
    make -j$CORES
fi

cd $PROJECT_DIR

